export const SUPPORTED_PROJECTS_STORAGE_KEY = "SUPPORTED_PROJECTS";
export const COMMON_PREFERRED_STATUSES_STORAGE_KEY =
  "COMMON_PREFERRED_STATUSES";

export const START_AND_END_FIELDS_STORAGE_KEY =
  "START_AND_END_FIELDS_STORAGE_KEY";

export const COMMENTS_SETTINGS_STORAGE_KEY = "COMMENTS_SETTINGS";
